
export const SIGN_IN_REQUEST="SIGN_IN_REQUEST"
export const SIGN_IN_SUCCESS="SIGN_IN_SUCCESS"
export const SIGN_IN_FAILED="SIGN_IN_FAILED"

export const SIGN_UP_REQUEST="SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS="SIGN_UP_SUCCESS"
export const SIGN_UP_FAILED="SIGN_UP_FAILED"

export const REMOVE_ERROR="REMOVE_ERROR"